version: "3"

services:
  demo-ms:
    image: demo:latest
    container_name: demo
    build:
      context: log
      dockerfile: Dockerfile
    tty: true
    ports:
      - "8080:8082"
    expose:
      - "80"
    restart: on-failure
    volumes:
      - /root/.m2:/root/.m2